version: "3.2"
services:
  php:
    image: miplanserviciosofial.azurecr.io/php:v1
    networks:
      - mired
  apache:
    image: miplanserviciosofial.azurecr.io/apache:v1
    depends_on:
      - php
      - mysql
    networks:
      - mired
    ports:
      - "8080:80"
  mysql:
    image: miplanserviciosofial.azurecr.io/mysql:v1
    networks:
      - mired
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  mired:
